export {
  diagnosticsInputSchema,
  diagnosticsOutputSchema,
  type DiagnosticsInput,
} from './diagnostics.schema.js';

export {
  crmObjectTypeSchema,
  associableObjectTypeSchema,
  recordIdSchema,
  propertyBagSchema,
  propertyValueSchema,
  searchOperatorSchema,
  getRecordInputSchema,
  searchRecordsInputSchema,
  createRecordInputSchema,
  updateRecordInputSchema,
  deleteRecordInputSchema,
  restoreRecordInputSchema,
  mergeRecordsInputSchema,
  batchRecordsInputSchema,
  manageAssociationsInputSchema,
  createEngagementInputSchema,
  getTimelineInputSchema,
  managePropertiesInputSchema,
  listPipelinesInputSchema,
  recordOutputSchema,
  recordPageOutputSchema,
  batchOutcomeOutputSchema,
  operationResultSchema,
  associationResultSchema,
  engagementOutputSchema,
  timelineOutputSchema,
  propertyResultSchema,
  pipelinesOutputSchema,
  type GetRecordInput,
  type SearchRecordsInput,
  type CreateRecordInput,
  type UpdateRecordInput,
  type DeleteRecordInput,
  type RestoreRecordInput,
  type MergeRecordsInput,
  type BatchRecordsInput,
  type ManageAssociationsInput,
  type CreateEngagementInput,
  type GetTimelineInput,
  type ManagePropertiesInput,
  type ListPipelinesInput,
  type NoteBody,
  type TaskBody,
  type CallBody,
  type MeetingBody,
  type EmailBody,
} from './crm.schema.js';
